name: open_eraa
channels:
- bioconda
- conda-forge
- ibmdecisionoptimization
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- _python_abi3_support=1.0=hd8ed1ab_2
- adwaita-icon-theme=49.0=unix_0
- affine=2.4.0=pyhd8ed1ab_1
- aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
- aiohttp=3.13.2=py312h27b7581_0
- aiosignal=1.4.0=pyhd8ed1ab_0
- alsa-lib=1.2.14=hb9d3cd8_0
- ampl-asl=1.0.0=h5888daf_2
- amply=0.1.6=pyhd8ed1ab_1
- anyio=4.12.0=pyhcf101f3_0
- appdirs=1.4.4=pyhd8ed1ab_1
- argon2-cffi=25.1.0=pyhd8ed1ab_0
- argon2-cffi-bindings=25.1.0=py312h4c3975b_2
- argparse-dataclass=2.0.0=pyhd8ed1ab_1
- arrow=1.4.0=pyhcf101f3_0
- astroid=4.0.2=py312h7900ff3_0
- asttokens=3.0.1=pyhd8ed1ab_0
- async-lru=2.0.5=pyh29332c3_0
- at-spi2-atk=2.38.0=h0630a04_3
- at-spi2-core=2.40.3=h0630a04_0
- atk-1.0=2.38.0=h04ea711_2
- attr=2.5.2=h39aace5_0
- attrs=25.4.0=pyhcf101f3_1
- aws-c-auth=0.9.3=hef928c7_0
- aws-c-cal=0.9.13=h2c9d079_1
- aws-c-common=0.12.6=hb03c661_0
- aws-c-compression=0.3.1=h8b1a151_9
- aws-c-event-stream=0.5.7=h28f887f_1
- aws-c-http=0.10.7=ha8fc4e3_5
- aws-c-io=0.23.3=hdaf4b65_5
- aws-c-mqtt=0.13.3=hc63082f_11
- aws-c-s3=0.11.3=h06ab39a_1
- aws-c-sdkutils=0.2.4=h8b1a151_4
- aws-checksums=0.2.7=h8b1a151_5
- aws-crt-cpp=0.35.4=h8824e59_0
- aws-sdk-cpp=1.11.606=h20b40b1_10
- azure-core-cpp=1.16.1=h3a458e0_0
- azure-identity-cpp=1.13.2=h3a5f585_1
- azure-storage-blobs-cpp=12.15.0=h2a74896_1
- azure-storage-common-cpp=12.11.0=h3d7a050_1
- azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
- babel=2.17.0=pyhd8ed1ab_0
- backports.zstd=1.2.0=py312h90b7ffd_0
- beautifulsoup4=4.14.3=pyha770c72_0
- bleach=6.3.0=pyhcf101f3_0
- bleach-with-css=6.3.0=h5f6438b_0
- blosc=1.21.6=he440d0b_1
- bokeh=3.8.1=pyhd8ed1ab_0
- bottleneck=1.6.0=np2py312hfb8c2c5_3
- branca=0.8.2=pyhd8ed1ab_0
- brotli=1.2.0=hed03a55_1
- brotli-bin=1.2.0=hb03c661_1
- brotli-python=1.2.0=py312hdb49522_1
- bzip2=1.0.8=hda65f42_8
- c-ares=1.34.6=hb03c661_0
- c-blosc2=2.22.0=hc31b594_1
- ca-certificates=2025.11.12=hbd8a1cb_0
- cached-property=1.5.2=hd8ed1ab_1
- cached_property=1.5.2=pyha770c72_1
- cachetools=6.2.2=pyhd8ed1ab_0
- cairo=1.18.4=h3394656_0
- cartopy=0.25.0=py312hf79963d_1
- certifi=2025.11.12=pyhd8ed1ab_0
- cffi=2.0.0=py312h460c074_1
- cfgv=3.5.0=pyhd8ed1ab_0
- cftime=1.6.4=py312h4f23490_2
- charset-normalizer=3.4.4=pyhd8ed1ab_0
- click=8.3.1=pyh8f84b5b_1
- click-plugins=1.1.1.2=pyhd8ed1ab_0
- cligj=0.7.2=pyhd8ed1ab_2
- cloudpickle=3.1.2=pyhcf101f3_1
- coin-or-cbc=2.10.12=h4d16d09_4
- coin-or-cgl=0.60.9=hc46dffc_6
- coin-or-clp=1.17.10=hc03379b_3
- coin-or-osi=0.108.11=hf4fecb4_8
- coin-or-utils=2.11.12=hc93afbd_7
- colorama=0.4.6=pyhd8ed1ab_1
- comm=0.2.3=pyhe01879c_0
- conda-inject=1.3.2=pyhd8ed1ab_0
- configargparse=1.7.1=pyhe01879c_0
- connection_pool=0.0.3=pyhd3deb0d_0
- contourpy=1.3.3=py312hd9148b4_3
- country_converter=1.3.2=pyhd8ed1ab_0
- cplex=22.1.2=py312_0
- cppad=20250000.2=h5888daf_0
- cpython=3.12.12=py312hd8ed1ab_1
- cryptography=46.0.3=py312ha4b625e_1
- cycler=0.12.1=pyhcf101f3_2
- cyrus-sasl=2.1.28=hd9c7081_0
- cytoolz=1.1.0=py312h4c3975b_1
- dask=2025.11.0=pyhcf101f3_0
- dask-core=2025.11.0=pyhcf101f3_0
- dbus=1.16.2=h24cb091_1
- debugpy=1.8.17=py312h8285ef7_1
- decorator=5.2.1=pyhd8ed1ab_0
- defusedxml=0.7.1=pyhd8ed1ab_0
- deprecation=2.1.0=pyh9f0ad1d_0
- descartes=1.1.0=pyhd8ed1ab_5
- dill=0.4.0=pyhcf101f3_1
- distlib=0.4.0=pyhd8ed1ab_0
- distributed=2025.11.0=pyhcf101f3_0
- docutils=0.22.3=pyhd8ed1ab_0
- dpath=2.2.0=pyha770c72_1
- entsoe-py=0.7.8=pyhd8ed1ab_0
- epoxy=1.5.10=hb03c661_2
- et_xmlfile=2.0.0=pyhd8ed1ab_1
- exceptiongroup=1.3.1=pyhd8ed1ab_0
- executing=2.2.1=pyhd8ed1ab_0
- filelock=3.20.0=pyhd8ed1ab_0
- fiona=1.10.1=py312h1289d80_4
- folium=0.20.0=pyhd8ed1ab_0
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=3.000=h77eed37_0
- font-ttf-source-code-pro=2.038=h77eed37_0
- font-ttf-ubuntu=0.83=h77eed37_3
- fontconfig=2.15.0=h7e30c49_1
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=hc364b38_1
- fonttools=4.61.0=py312h8a5da7c_0
- fqdn=1.5.1=pyhd8ed1ab_1
- freetype=2.14.1=ha770c72_0
- freexl=2.0.0=h9dce30a_2
- fribidi=1.0.16=hb03c661_0
- frozenlist=1.7.0=py312h447239a_0
- fsspec=2025.12.0=pyhd8ed1ab_0
- gdk-pixbuf=2.44.4=h2b0a6b4_0
- geographiclib=2.1=pyhd8ed1ab_0
- geojson=3.2.0=pyhd8ed1ab_0
- geopandas=1.1.1=pyhd8ed1ab_1
- geopandas-base=1.1.1=pyha770c72_1
- geopy=2.4.1=pyhd8ed1ab_2
- geos=3.14.1=h480dda7_0
- geotiff=1.7.4=h1000f5c_4
- gflags=2.2.2=h5888daf_1005
- giflib=5.2.2=hd590300_0
- gitdb=4.0.12=pyhd8ed1ab_0
- gitpython=3.1.45=pyhff2d567_0
- glib=2.86.3=h5192d8d_0
- glib-tools=2.86.3=hf516916_0
- glog=0.7.1=hbabe93e_0
- glpk=5.0=h445213a_0
- gmp=6.3.0=hac33072_2
- google-api-core=2.28.1=pyhd8ed1ab_0
- google-auth=2.43.0=pyhd8ed1ab_0
- google-cloud-core=2.5.0=pyhd8ed1ab_0
- google-cloud-storage=3.7.0=pyhcf101f3_0
- google-crc32c=1.7.1=py312h03f33d3_1
- google-resumable-media=2.8.0=pyhd8ed1ab_0
- googleapis-common-protos=1.72.0=pyhd8ed1ab_0
- graphite2=1.3.14=hecca717_2
- graphviz=14.1.0=h8b86629_0
- grpcio=1.73.1=py312h6f3464c_1
- grpcio-status=1.73.1=pyhd8ed1ab_0
- gst-plugins-base=1.24.11=h651a532_0
- gstreamer=1.24.11=hc37bda9_0
- gtk3=3.24.43=h993cebd_6
- gts=0.7.6=h977cf35_4
- h11=0.16.0=pyhd8ed1ab_0
- h2=4.3.0=pyhcf101f3_0
- harfbuzz=12.2.0=h15599e2_0
- hdf4=4.2.15=h2a13503_7
- hdf5=1.14.6=nompi_h1b119a7_104
- hicolor-icon-theme=0.17=ha770c72_2
- hpack=4.1.0=pyhd8ed1ab_0
- httpcore=1.0.9=pyh29332c3_0
- httpx=0.28.1=pyhd8ed1ab_0
- humanfriendly=10.0=pyh707e725_8
- hyperframe=6.1.0=pyhd8ed1ab_0
- icu=75.1=he02047a_0
- identify=2.6.15=pyhd8ed1ab_0
- idna=3.11=pyhd8ed1ab_0
- immutables=0.21=py312h4c3975b_2
- importlib-metadata=8.7.0=pyhe01879c_1
- importlib_resources=6.5.2=pyhd8ed1ab_0
- ipopt=3.14.19=h0804adb_0
- ipykernel=7.1.0=pyha191276_0
- ipython=9.8.0=pyh53cf698_0
- ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
- ipywidgets=8.1.8=pyhd8ed1ab_0
- isoduration=20.11.0=pyhd8ed1ab_1
- isort=7.0.0=pyhd8ed1ab_0
- jedi=0.19.2=pyhd8ed1ab_1
- jinja2=3.1.6=pyhcf101f3_1
- joblib=1.5.2=pyhd8ed1ab_0
- jpype1=1.6.0=py312hd9148b4_1
- json-c=0.18=h6688a6e_0
- json5=0.12.1=pyhd8ed1ab_0
- jsonpointer=3.0.0=pyhcf101f3_3
- jsonschema=4.25.1=pyhe01879c_0
- jsonschema-specifications=2025.9.1=pyhcf101f3_0
- jsonschema-with-format-nongpl=4.25.1=he01879c_0
- jupyter=1.1.1=pyhd8ed1ab_1
- jupyter-lsp=2.3.0=pyhcf101f3_0
- jupyter_client=8.7.0=pyhcf101f3_0
- jupyter_console=6.6.3=pyhd8ed1ab_1
- jupyter_core=5.9.1=pyhc90fa1f_0
- jupyter_events=0.12.0=pyh29332c3_0
- jupyter_server=2.17.0=pyhcf101f3_0
- jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
- jupyterlab=4.5.0=pyhd8ed1ab_0
- jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
- jupyterlab_server=2.28.0=pyhcf101f3_0
- jupyterlab_widgets=3.0.16=pyhcf101f3_1
- keyutils=1.6.3=hb9d3cd8_0
- kiwisolver=1.4.9=py312h0a2e395_2
- krb5=1.21.3=h659f571_0
- lame=3.100=h166bdaf_1003
- lark=1.3.1=pyhd8ed1ab_0
- lcms2=2.17=h717163a_0
- ld_impl_linux-64=2.45=default_hbd61a6d_104
- legacy-cgi=2.6.4=pyhcf101f3_0
- lerc=4.0.0=h0aef613_1
- libabseil=20250512.1=cxx17_hba17884_0
- libaec=1.1.4=h3f801dc_0
- libarchive=3.8.2=gpl_h7be2006_100
- libarrow=22.0.0=hb6ed5f4_6_cpu
- libarrow-acero=22.0.0=h635bf11_6_cpu
- libarrow-compute=22.0.0=h8c2c5c3_6_cpu
- libarrow-dataset=22.0.0=h635bf11_6_cpu
- libarrow-substrait=22.0.0=h3f74fd7_6_cpu
- libblas=3.11.0=4_h4a7cf45_openblas
- libbrotlicommon=1.2.0=hb03c661_1
- libbrotlidec=1.2.0=hb03c661_1
- libbrotlienc=1.2.0=hb03c661_1
- libcap=2.77=h3ff7636_0
- libcblas=3.11.0=4_h0358290_openblas
- libclang-cpp21.1=21.1.7=default_h99862b1_1
- libclang13=21.1.7=default_h746c552_1
- libcrc32c=1.1.2=h9c3ff4c_0
- libcups=2.3.3=hb8b1518_5
- libcurl=8.17.0=h4e3cde8_1
- libdeflate=1.25=h17f619e_0
- libdrm=2.4.125=hb03c661_1
- libedit=3.1.20250104=pl5321h7949ede_0
- libegl=1.7.0=ha4b6fd6_2
- libegl-devel=1.7.0=ha4b6fd6_2
- libev=4.33=hd590300_2
- libevent=2.1.12=hf998b51_1
- libexpat=2.7.3=hecca717_0
- libffi=3.5.2=h9ec8514_0
- libflac=1.5.0=he200343_1
- libfreetype=2.14.1=ha770c72_0
- libfreetype6=2.14.1=h73754d4_0
- libgcc=15.2.0=he0feb66_16
- libgcc-ng=15.2.0=h69a702a_16
- libgd=2.3.3=h6f5c62b_11
- libgdal-core=3.10.3=h1f481a6_27
- libgdal-hdf4=3.10.3=ha810028_27
- libgdal-hdf5=3.10.3=h966a9c2_27
- libgdal-netcdf=3.10.3=ha526aae_27
- libgfortran=15.2.0=h69a702a_16
- libgfortran-ng=15.2.0=h69a702a_16
- libgfortran5=15.2.0=h68bc16d_16
- libgl=1.7.0=ha4b6fd6_2
- libgl-devel=1.7.0=ha4b6fd6_2
- libglib=2.86.3=h6548e54_0
- libglvnd=1.7.0=ha4b6fd6_2
- libglx=1.7.0=ha4b6fd6_2
- libglx-devel=1.7.0=ha4b6fd6_2
- libgomp=15.2.0=he0feb66_16
- libgoogle-cloud=2.39.0=hdb79228_0
- libgoogle-cloud-storage=2.39.0=hdbdcf42_0
- libgrpc=1.73.1=h3288cfb_1
- libhwloc=2.12.1=default_hafda6a7_1003
- libiconv=1.18=h3b78370_2
- libjpeg-turbo=3.1.2=hb03c661_0
- libkml=1.3.0=haa4a5bd_1022
- liblapack=3.11.0=4_h47877c9_openblas
- liblapacke=3.11.0=4_h6ae95b6_openblas
- libllvm21=21.1.7=hf7376ad_0
- liblzma=5.8.1=hb9d3cd8_2
- liblzma-devel=5.8.1=hb9d3cd8_2
- libnetcdf=4.9.3=nompi_h11f7409_103
- libnghttp2=1.67.0=had1ee68_0
- libnsl=2.0.1=hb9d3cd8_1
- libntlm=1.8=hb9d3cd8_0
- libogg=1.3.5=hd0c01bc_1
- libopenblas=0.3.30=pthreads_h94d23a6_4
- libopengl=1.7.0=ha4b6fd6_2
- libopentelemetry-cpp=1.21.0=hb9b0907_1
- libopentelemetry-cpp-headers=1.21.0=ha770c72_1
- libopus=1.5.2=hd0c01bc_0
- libparquet=22.0.0=h7376487_6_cpu
- libpciaccess=0.18=hb9d3cd8_0
- libpng=1.6.53=h421ea60_0
- libpq=18.1=h5c52fec_2
- libprotobuf=6.31.1=h49aed37_2
- libre2-11=2025.11.05=h7b12aa8_0
- librsvg=2.60.0=h61e6d4b_0
- librttopo=1.1.0=h46dd2a8_20
- libscotch=7.0.4=h2fe6a88_5
- libsndfile=1.2.2=hc7d488a_2
- libsodium=1.0.20=h4ab18f5_0
- libspatialite=5.1.0=gpl_h2abfd87_119
- libspral=2025.05.20=hfabd9d1_1
- libsqlite=3.51.1=h0c1763c_0
- libssh2=1.11.1=hcf80075_0
- libstdcxx=15.2.0=h934c35e_16
- libstdcxx-ng=15.2.0=hdf11a46_16
- libsystemd0=257.10=hd0affe5_2
- libthrift=0.22.0=h454ac66_1
- libtiff=4.7.1=h9d88235_1
- libutf8proc=2.11.2=hfe17d71_0
- libuuid=2.41.2=h5347b49_1
- libvorbis=1.3.7=h54a6638_2
- libwebp-base=1.6.0=hd42ef1d_0
- libxcb=1.17.0=h8a09558_0
- libxcrypt=4.4.36=hd590300_1
- libxkbcommon=1.13.1=hca5e8e5_0
- libxml2=2.15.1=h26afc86_0
- libxml2-16=2.15.1=ha9997c6_0
- libxml2-devel=2.15.1=h26afc86_0
- libxslt=1.1.43=h711ed8c_1
- libzip=1.11.2=h6991a6a_0
- libzlib=1.3.1=hb9d3cd8_2
- linopy=0.5.8=pyhd8ed1ab_0
- locket=1.0.0=pyhd8ed1ab_0
- lxml=6.0.2=py312h63ddcf0_2
- lz4=4.4.5=py312h3d67a73_1
- lz4-c=1.10.0=h5888daf_1
- lzo=2.10=h280c20c_1002
- mapclassify=2.10.0=pyhd8ed1ab_1
- markupsafe=3.0.3=py312h8a5da7c_0
- matplotlib=3.9.1=py312h7900ff3_1
- matplotlib-base=3.9.1=py312h854627b_2
- matplotlib-inline=0.2.1=pyhd8ed1ab_0
- mccabe=0.7.0=pyhd8ed1ab_1
- memory_profiler=0.61.0=pyhcf101f3_1
- metis=5.1.0=hd0bcaf9_1007
- minizip=4.0.10=h05a5f5f_0
- mistune=3.1.4=pyhcf101f3_0
- mpfr=4.2.1=h90cbb55_3
- mpg123=1.32.9=hc50e24c_0
- msgpack-python=1.1.2=py312hd9148b4_1
- multidict=6.6.3=py312h178313f_0
- mumps-include=5.7.3=h82cca05_10
- mumps-seq=5.7.3=h27a6a8b_0
- munkres=1.1.4=pyhd8ed1ab_1
- narwhals=2.13.0=pyhcf101f3_0
- nbclient=0.10.2=pyhd8ed1ab_0
- nbconvert-core=7.16.6=pyhcf101f3_1
- nbformat=5.10.4=pyhd8ed1ab_1
- ncurses=6.5=h2d0b736_3
- nest-asyncio=1.6.0=pyhd8ed1ab_1
- netcdf4=1.7.3=nompi_py312hf6400b3_100
- networkx=3.6.1=pyhcf101f3_0
- nlohmann_json=3.12.0=h54a6638_1
- nodeenv=1.9.1=pyhd8ed1ab_1
- nomkl=1.0=h5ca1d4c_0
- notebook=7.5.0=pyhcf101f3_0
- notebook-shim=0.2.4=pyhd8ed1ab_1
- nspr=4.38=h29cc59b_0
- nss=3.118=h445c969_0
- numexpr=2.14.1=py312h88efc94_101
- numpy=1.26.4=py312heda63a1_0
- openjpeg=2.5.4=h55fea9a_0
- openldap=2.6.10=he970967_0
- openpyxl=3.1.5=py312h7f6eeab_2
- openssl=3.6.0=h26f9b46_0
- orc=2.2.1=hd747db4_0
- overrides=7.7.0=pyhd8ed1ab_1
- packaging=25.0=pyh29332c3_1
- pandas=2.3.3=py312hf79963d_1
- pandocfilters=1.5.0=pyhd8ed1ab_0
- pango=1.56.4=hadf4263_0
- parso=0.8.5=pyhcf101f3_0
- partd=1.4.2=pyhd8ed1ab_0
- patsy=1.0.2=pyhcf101f3_0
- pcre2=10.47=haa7fec5_0
- pexpect=4.9.0=pyhd8ed1ab_1
- pillow=12.0.0=py312h50c33e8_2
- pip=25.3=pyh8b19718_0
- pixman=0.46.4=h54a6638_1
- platformdirs=4.5.1=pyhcf101f3_0
- ply=3.11=pyhd8ed1ab_3
- polars=1.36.1=pyh6a1acc5_0
- polars-runtime-32=1.36.1=py310hffdcd12_0
- powerplantmatching=0.7.1=pyhd8ed1ab_0
- pre-commit=4.5.0=pyha770c72_0
- proj=9.7.1=h99ae125_0
- prometheus-cpp=1.3.0=ha5d0236_0
- prometheus_client=0.23.1=pyhd8ed1ab_0
- prompt-toolkit=3.0.52=pyha770c72_0
- prompt_toolkit=3.0.52=hd8ed1ab_0
- propcache=0.3.1=py312h178313f_0
- proto-plus=1.26.1=pyhd8ed1ab_0
- protobuf=6.31.1=py312hb8af0ac_2
- psutil=7.1.3=py312h5253ce2_0
- pthread-stubs=0.4=hb9d3cd8_1002
- ptyprocess=0.7.0=pyhd8ed1ab_1
- pulp=2.8.0=py312hd0750ca_3
- pulseaudio-client=17.0=h9a6aba3_3
- pure_eval=0.2.3=pyhd8ed1ab_1
- py-cpuinfo=9.0.0=pyhd8ed1ab_1
- pyarrow=22.0.0=py312h7900ff3_0
- pyarrow-core=22.0.0=py312hc195796_0_cpu
- pyasn1=0.6.1=pyhd8ed1ab_2
- pyasn1-modules=0.4.2=pyhd8ed1ab_0
- pycountry=24.6.1=pyhd8ed1ab_0
- pycparser=2.22=pyh29332c3_1
- pygments=2.19.2=pyhd8ed1ab_0
- pylint=4.0.4=pyhcf101f3_0
- pyogrio=0.11.0=py312h02b19dd_0
- pyopenssl=25.3.0=pyhd8ed1ab_0
- pyparsing=3.2.5=pyhcf101f3_0
- pyproj=3.7.2=py312h9b6a7d9_2
- pyqt=5.15.11=py312h82c0db2_2
- pyqt5-sip=12.17.0=py312h1289d80_2
- pyscipopt=5.6.0=py312h1289d80_1
- pyshp=3.0.3=pyhd8ed1ab_0
- pysocks=1.7.1=pyha55dd90_7
- pytables=3.10.2=py312hefc0c3f_10
- python=3.12.12=hd63d673_1_cpython
- python-dateutil=2.9.0.post0=pyhe01879c_2
- python-fastjsonschema=2.21.2=pyhe01879c_0
- python-gil=3.12.12=hd8ed1ab_1
- python-json-logger=2.0.7=pyhd8ed1ab_0
- python-tzdata=2025.2=pyhd8ed1ab_0
- python_abi=3.12=8_cp312
- pytz=2025.2=pyhd8ed1ab_0
- pyu2f=0.1.5=pyhd8ed1ab_1
- pyxlsb=1.0.10=pyhd8ed1ab_0
- pyyaml=6.0.3=py312h8a5da7c_0
- pyzmq=27.1.0=py312hfb55c3c_0
- qhull=2020.2=h434a139_5
- qt-main=5.15.15=h3c3fd16_6
- rasterio=1.4.3=py312h762fea3_3
- re2=2025.11.05=h5301d42_0
- readline=8.2=h8c095d6_2
- referencing=0.37.0=pyhcf101f3_0
- requests=2.32.5=pyhd8ed1ab_0
- reretry=0.11.8=pyhd8ed1ab_1
- rfc3339-validator=0.1.4=pyhd8ed1ab_1
- rfc3986-validator=0.1.1=pyh9f0ad1d_0
- rfc3987-syntax=1.1.0=pyhe01879c_1
- rioxarray=0.20.0=pyhd8ed1ab_0
- rpds-py=0.30.0=py312h868fb18_0
- rsa=4.9.1=pyhd8ed1ab_0
- ruff=0.14.8=h813ae00_0
- s2n=1.6.2=he8a4886_1
- scikit-learn=1.8.0=py312h4f0b9e3_0
- scip=9.2.4=hd8b5c82_2
- scipy=1.16.3=py312h7a1785b_1
- seaborn=0.13.2=hd8ed1ab_3
- seaborn-base=0.13.2=pyhd8ed1ab_3
- send2trash=1.8.3=pyh0d859eb_1
- setuptools=80.9.0=pyhff2d567_0
- shapely=2.1.2=py312h383787d_2
- sip=6.10.0=py312h1289d80_1
- six=1.17.0=pyhe01879c_1
- smart_open=7.5.0=pyhcf101f3_0
- smmap=5.0.2=pyhd8ed1ab_0
- snakemake-executor-plugin-cluster-generic=1.0.9=pyhdfd78af_0
- snakemake-executor-plugin-slurm=2.0.0=pyhdfd78af_0
- snakemake-executor-plugin-slurm-jobstep=0.3.0=pyhdfd78af_0
- snakemake-interface-common=1.22.0=pyhd4c3c12_0
- snakemake-interface-executor-plugins=9.3.9=pyhdfd78af_0
- snakemake-interface-logger-plugins=2.0.0=pyhd4c3c12_0
- snakemake-interface-report-plugins=1.3.0=pyhd4c3c12_0
- snakemake-interface-scheduler-plugins=2.0.2=pyhd4c3c12_0
- snakemake-interface-storage-plugins=4.3.2=pyhd4c3c12_0
- snakemake-minimal=9.14.3=pyhdfd78af_0
- snappy=1.2.2=h03e3b7b_1
- sniffio=1.3.1=pyhd8ed1ab_2
- snuggs=1.4.7=pyhd8ed1ab_2
- sortedcontainers=2.4.0=pyhd8ed1ab_1
- soupsieve=2.8=pyhd8ed1ab_0
- sqlite=3.51.1=hbc0de68_0
- stack_data=0.6.3=pyhd8ed1ab_1
- statsmodels=0.14.6=py312h4f23490_0
- tabulate=0.9.0=pyhcf101f3_3
- tbb=2022.3.0=h8d10470_1
- tblib=3.2.2=pyhcf101f3_0
- terminado=0.18.1=pyh0d859eb_0
- threadpoolctl=3.6.0=pyhecae5ae_0
- throttler=1.2.2=pyhd8ed1ab_0
- tinycss2=1.5.1=pyhcf101f3_0
- tk=8.6.13=noxft_ha0e22de_103
- toml=0.10.2=pyhcf101f3_3
- tomli=2.3.0=pyhcf101f3_0
- tomlkit=0.13.3=pyha770c72_0
- toolz=1.1.0=pyhd8ed1ab_1
- tornado=6.5.2=py312h4c3975b_2
- tqdm=4.67.1=pyhd8ed1ab_1
- traitlets=5.14.3=pyhd8ed1ab_1
- typing-extensions=4.15.0=h396c80c_0
- typing_extensions=4.15.0=pyhcf101f3_0
- typing_utils=0.1.0=pyhd8ed1ab_1
- tzdata=2025b=h78e105d_0
- ukkonen=1.0.1=py312hd9148b4_6
- unicodedata2=17.0.0=py312h4c3975b_1
- unidecode=1.4.0=pyhcf101f3_1
- uri-template=1.3.0=pyhd8ed1ab_1
- uriparser=0.9.8=hac33072_0
- urllib3=2.6.1=pyhd8ed1ab_0
- virtualenv=20.35.4=pyhd8ed1ab_0
- wayland=1.24.0=hd6090a7_1
- wcwidth=0.2.14=pyhd8ed1ab_0
- webcolors=25.10.0=pyhd8ed1ab_0
- webencodings=0.5.1=pyhd8ed1ab_3
- websocket-client=1.9.0=pyhd8ed1ab_0
- wheel=0.45.1=pyhd8ed1ab_1
- widgetsnbextension=4.0.15=pyhd8ed1ab_0
- wrapt=1.17.3=py312h4c3975b_1
- xarray=2025.6.1=pyhd8ed1ab_1
- xcb-util=0.4.1=h4f16b4b_2
- xcb-util-image=0.4.0=hb711507_2
- xcb-util-keysyms=0.4.1=hb711507_0
- xcb-util-renderutil=0.3.10=hb711507_0
- xcb-util-wm=0.4.2=hb711507_0
- xerces-c=3.3.0=h988505b_0
- xkeyboard-config=2.46=hb03c661_0
- xlrd=2.0.2=pyhd8ed1ab_0
- xorg-libice=1.1.2=hb9d3cd8_0
- xorg-libsm=1.2.6=he73a12e_0
- xorg-libx11=1.8.12=h4f16b4b_0
- xorg-libxau=1.0.12=hb03c661_1
- xorg-libxcomposite=0.4.6=hb9d3cd8_2
- xorg-libxcursor=1.2.3=hb9d3cd8_0
- xorg-libxdamage=1.1.6=hb9d3cd8_0
- xorg-libxdmcp=1.1.5=hb03c661_1
- xorg-libxext=1.3.6=hb9d3cd8_0
- xorg-libxfixes=6.0.2=hb03c661_0
- xorg-libxi=1.8.2=hb9d3cd8_0
- xorg-libxinerama=1.1.5=h5888daf_1
- xorg-libxrandr=1.5.4=hb9d3cd8_0
- xorg-libxrender=0.9.12=hb9d3cd8_0
- xorg-libxshmfence=1.3.3=hb9d3cd8_0
- xorg-libxtst=1.2.5=hb9d3cd8_3
- xorg-libxxf86vm=1.1.6=hb9d3cd8_0
- xorg-xorgproto=2024.1=hb9d3cd8_1
- xyzservices=2025.11.0=pyhd8ed1ab_0
- xz=5.8.1=hbcc6ac9_2
- xz-gpl-tools=5.8.1=hbcc6ac9_2
- xz-tools=5.8.1=hb9d3cd8_2
- yaml=0.2.5=h280c20c_3
- yarl=1.22.0=py312h8a5da7c_0
- yte=1.9.4=pyhd8ed1ab_0
- zeromq=4.3.5=h387f397_9
- zict=3.0.0=pyhd8ed1ab_1
- zipp=3.23.0=pyhcf101f3_1
- zlib=1.3.1=hb9d3cd8_2
- zlib-ng=2.3.2=h54a6638_0
- zstd=1.5.7=hb78ec9c_6

